name: Local Build

on: 
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

jobs:
  buildForAllSupportedPlatforms:
    name: Buildeando ese Paquero
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Build
        shell: pwsh
        run: |
          .\build_win64.ps1 ${{ steps.tagName.outputs.tag }}