name: Local Build

on: 
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

jobs:
  buildForAllSupportedPlatforms:
    name: Buildeando ese Paquero
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: actions/cache@v2
        with:
          path: |
            .\Bug_And_Soft
          key: v1.0.73
      - name: Build
        shell: pwsh
        run: |
          .\build_win64.ps1 ${{ steps.tagName.outputs.tag }}