name: Build project

on: 
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'


jobs:
  buildForAllSupportedPlatforms:
    name: Building ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          #- Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: ./build
      - uses: actions/upload-artifact@v2
        id: uarti
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Download artifact ${{ matrix.targetPlatform }}
        id: download
        uses: actions/download-artifact@v2
        with:
          path: Build-${{ matrix.targetPlatform }}
      - name: Download path
        run: echo "${{ steps.download.outputs.download-path }}"    
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}